### ISSUE TITLE
Is it possible to convert OSL to HLSL

### ISSUE THREAD

**Issue by ongamex** [imageworks/OpenShadingLanguage#1023]
Is it possible to convert OSL to HLSL?
I have a small game engine and I want to describe my materials/maps in OSL for cross application compatibility (like 3ds Max + the game engine).

**Comment by lgritz** [comment]
Hi, it's really better to use the osl-dev mail list for questions like this. We generally use the GitHub "Issues" for reporting verifiable bugs.

That said, it depends on what mean by "possible." It's certainly possible, and 3dsmax does so to visualize OSL shaders in the viewport). But the OSL open source project does not currently have any functionality that does that translation.

I'm going to close because this isn't really an issue as we use them.

**Comment by alexkowel** [comment]
Check out OSL to GLSL converter [here](https://github.com/Soft8Soft/pyosl).

**Comment by lgritz** [comment]
@alexkowel That's a cool project, thanks for the pointer!

Maybe I don't fully understand it, but from the README and a quick browse of the code, it looks like it parses a single osl source file to an AST, then writes it back out with a straightforward translation of the AST to GLSL. But most people write big complex networks of connected nodes -- shader groups.

I think that the solution we want (in the OSL code base, at least) is going to let the existing library assemble the shader group, read the .oso's, do the full "runtime optimization" of the group... and right when, now, it would turn the resulting in-memory oso representation into LLVM IR, it would instead write GLSL/HLSL/whatever for the whole optimized group. And it would need to do it in conjunction with the renderer also providing the snippets of GLSL/HLSL that would compute the lighting and evaluate the BSDFs implied by the closures, and implement all the other bits of functionality that the RendererServices API would perform in a CPU renderer. So it would hand OpenGL a complete GLSL shader all ready to run and produce the same picture that the regular CPU path in that renderer would have produced (or at least, as close as possible) for the whole shader group.

**Comment by alexkowel** [comment]
Yep, the pyosl translator is quite simple. The main idea behind this project was to convert OSL shaders that are shipped with 3ds Max to be rendered in WebGL (using the Verge3D framework). The approach with intermediate bytecode looks really promising, however, we don't have enough experience with LLVM and C++ to handle it ourselves. Hope somebody will handle it because I believe there is a great opportunity for OSL to become the number one solution not only for hardcore raytraced rendering but for realtime as well.
