### ISSUE TITLE
build broken/CMake complains about missing C++14 support in clang on macOS

### ISSUE THREAD

**Issue by virtualritz** [imageworks/OpenShadingLanguage#1205]
I'm trying to build on macOS 10.15.4. All deps are installed.
I could install LLVM (via homebrew) but I'd prefer if I can the installed one from Apple.

Anyone seen this – is there a straightforward solution?
```
❯ make
-- Building OSL 1.11.6.0
-- CMake version is 3.17.3
-- Configuring OSL 1.11.6.0
-- CMake 3.17.3
-- CMake system           = Darwin-19.5.0
-- CMake system name      = Darwin
-- Project source dir     = /Users/moritz/code/OpenShadingLanguage
-- Project build dir      = /Users/moritz/code/OpenShadingLanguage/build/macosx
-- Project install prefix = /Users/moritz/code/OpenShadingLanguage/dist/macosx
-- Configuration types    =
-- Build type             = Release
-- Setting Namespace to: OSL_v1_11
-- CMAKE_CXX_COMPILER     = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- CMAKE_CXX_COMPILER_ID  = AppleClang
-- Building for C++11
-- clang-format found: /usr/local/bin/clang-format
--
-- * Checking for dependencies...
-- *   - Missing a dependency 'Package'?
-- *     Try cmake -DPackage_ROOT=path or set environment var Package_ROOT=path
-- *     For many dependencies, we supply src/build-scripts/build_Package.bash
-- *   - To exclude an optional dependency (even if found),
-- *     -DUSE_Package=OFF or set environment var USE_Package=OFF
--
-- Found Boost 107200
-- Found ZLIB 1.2.11
-- Found OpenEXR 2.5.1
-- Found OpenImageIO 2.1.16.0
-- Found PugiXML
-- Found LLVM 10.0.0
CMake Error at src/cmake/externalpackages.cmake:247 (message):
  LLVM 10+ requires C++14 or higher (was 11).
Call Stack (most recent call first):
  CMakeLists.txt:134 (include)
```

**Comment by fpsunflower** [comment]
Try `make USE_CPP=14` to tell it to use c++14?

**Comment by lgritz** [comment]
Right. If you want LLVM 10, you MUST use C++14 or higher.

The modern idiom is `CMAKE_CXX_STANDARD=14`, though `USE_CPP=14` still works as a synonym.

**Comment by lgritz** [comment]
I'll try to make a more prescriptive error message in this case.

**Comment by virtualritz** [comment]
I do not necessarily want LLVM 10. I just want the build to work with whatever LLVM is installed or tell me what to do/pass to the `make` invocation/environment to make it work.

On a sidenote: what I do not get is why the `CMakeLists` doesn't set `CMAKE_CXX_STANDARD=14`/`USE_CPP=14` itself when it finds a LLVM 10+.

Is there any reason not to set automatically in this case and just print a message for the user to make them aware? Isn't it safe to assume that this what the user wants?

**Comment by virtualritz** [comment]
Sorry if that came across as grumpy. `CMAKE_CXX_STANDARD=14 make` works. I think I'm just got used to amazing tooling after a year of Rust.

And this experience reminded me how bad things are in C++ land in comparison and how much burden is placed on both maintainers as well as users of a lib there to make things equally smooth.

Thanks heaps for caring & that PR – that is great build script UX! :)

**Comment by lgritz** [comment]
@virtualritz I'm guessing you use homebrew or some other package manager that upgraded your default llvm to 10 whether you wanted it or not. (If homebrew, then what you can do is install "llvm@9" and make sure your LLVM_DIRECTORY (or also LLVM_ROOT?) is set to the right place where it installed.

I'm a little wary about automatically bumping the CMAKE_CXX_STANDARD, that really is an orthogonal choice, and I can imagine other things going wrong if people think they are building for C++11 but it auto changes to 14. Also, by the time it gets to fully finding llvm and understanding what version it is, it's long past other decisions being made based on the compiler and C++ standard.

Currently, the default CMAKE_CXX_STANDARD (if you don't explicitly set it) is the minimum, which is 11. We could make the default 14, so if somebody wants 11 they would have to set it explicitly. That would make LLVM consistently work, but I can imagine it would break other people. Like, people still using gcc 4.8 would then have trouble.

Not sure there's a best or flawless solution here, so that's why I figured the most helpful thing is to just spell out all the issues in the error message.

**Comment by virtualritz** [comment]
Makes total sense.
And yes, homebrew is to blame.
