### ISSUE TITLE
Windows compile fixes

### ISSUE THREAD

**Issue by debaetsd** [imageworks/OpenShadingLanguage#1261]
### Problem

This issue is to discuss compiling OSL on Windows (MSVC 2019)
I have found multiple issues but I would like to discuss this here before making a PR as I'm not sure about some of them ("it works on my machine" )

1.  `src\liboslexec\llvm_instance.cpp` includes `cxxabi.h`. This is a GCC extension header (so include fails on MSVC) but I do not believe this is actually used? Simply commenting this line fixes it. This seemed to be added as part of the OPTIX changes but I have not actually tried compiling with `OSL_USE_OPTIX` so needs to be verified.
**Proposed solution:** remove that include
**risk:** low, if it compiles on all target platforms (+with optix enabled), it should be fine

2. 30+ linker errors when building oslquery or oslcomp. Virtually all of them can be tracked back to including of `oslexec_pvt.h`. This will define symbols inside various classes (llvm_util, rendererservices,..) but those projects to not have the implementations (those are only compiled by `oslexec`). Even though those functions/classes are not actually used, it does give errors. Changing the cmake setup to NOT setup `OSL_EXPORTS` fixes it as this marks those classes as `dllimport` (and so no implementation is expected). I believe this to be a correct solution (on Windows at least) but not to sure about this and would love input about it by somebody who knows the entire OSL ecosystem better.
**Proposed solution:** remove `target_compile_definitions (${local_lib} PRIVATE OSL_EXPORTS)` from the cmake setup of liboslcomp & liboslquery
**risk:**perhaps the biggest as this could influence how the libs/exe are generated on various compilers. 

3. Upon linking of liboslexec, unreferenced externals `GetFileVersionInfoSizeW` and `VerQueryValueW` are given when linking with ClangDriver.lib. These win32 functions seemed to be referenced by LLVM/Clang and in order make it work, linking with the system `MinCore.lib` library fixes it. This might be an issue related to LLVM (or how I compile it) though it seems this is an issue worked around in other libraries  (see for example https://github.com/andreasfertig/cppinsights/blob/master/CMakeLists.txt @ line 230). I worked around it by providing `-D CMAKE_CXX_STANDARD_LIBRARIES="MinCore.lib"` on the cmake cmd line. Perhaps modifying cmake inside OSL to link this library (on MSVC), might be a good idea (at worst it gets added to libraries to link with but it does not ends up using it ?)
**Proposed solution:** Modify cmake on MSVC to link with that system library
**risk:** low, should be validated with "official" windows llvm builds to exclude this is not a local issue (if this proposed fix makes sense)

As said, these changes were required to compile on my machine (excl python, tests & shaders atm).
Please discuss on what changes seem reasonable enough to be made into a PR .
I can verify/validate extra steps on windows if required.

### Versions

* OSL branch/version: 1.11.7.3 release
* OS: Win10
* C++ compiler: MSVC 19.27.29111.0
* LLVM version: 10.0.1 (with misc patch applied to make it compile on windows, https://reviews.llvm.org/D86126)
* OIIO version:  2.2.7.0
* -D CMAKE_CXX_STANDARD=14 -D USE_PYTHON=0 -D OSL_BUILD_TESTS=1 -D OSL_BUILD_SHADERS=0

**Comment by ix-dcourtois** [comment]
Hello there! Really glad you opened this issue, we're currently also having a bit of troubles building the latest OSL version :)

1/ I did fix this by embedding the `#include` in a `#ifdef __GNUC__` guard. Not sure if this is the best, but my reasoning is that it only removes the include where it's not supported, and does not modify the platforms where it's there.

2/ This one was the one I struggled with, and I didn't narrow down the issue to the `OSL_EXPORTS` preprocessor being incorrectly set! And my two cents: OSL_EXPORTS only impact Windows, and since on Windows the build is currently broken anyway, I think your solution is perfectly fine.

3/ Those missing external symbols are defined in `Version.lib` (see https://docs.microsoft.com/en-us/windows/win32/api/winver/nf-winver-verqueryvaluew, at the end of the page there's the lib it's defined in) In my fixes, I modified the CMake file to add this lib on Windows.

4/ There was also a problem when building shaders (e.g. `-DOSL_BUILD_SHADERS=1`) : oslc.exe needs olscomp.dll to work, and oslcomp.dll is built in a separate folder. I fixed this by changing the CMake to copy oslcomp.dll next to oslc.exe. But this change is less important, and I can submit this change as a separate pull request.


Anyways, I'd gladly see a pull request to fix the first 3 points :)

**Comment by debaetsd** [comment]
I created PR #1263 for issue 1-3

For me, trying to build shaders (issue 4) still gives errors. I might look into it later.

**Comment by lgritz** [comment]
I can't quite tell from the last two comments if point 4 is still a problem. (Was the "EDIT:" added after the subsequent comment?) Is this still an outstanding problem, or can we close this issue?

**Comment by ix-dcourtois** [comment]
Not sure about the author of the issue, but for me all points were fixed. I'm not sure what the errors @debaetsd still has, but it might be a simple case of setting the `%PATH%` env var to let `oslc` find its dependencies (OpenImageIO, etc.) At least in my build setup, this is the only thing I had to do to build the shaders, after the pull request was merged.

**Comment by debaetsd** [comment]
Building shaders works just fine for me. 
IIRC the reason for not adressing that 4th point in my PR was because I did not have them build as part of my setup so I could not be sure it was (not) working.
But just tried it and it seems to work for me without any changes
