### ISSUE TITLE
Custom Shadeops

### ISSUE THREAD

**Issue by ldmoser** [imageworks/OpenShadingLanguage#372]
I haven't found anything regarding extending OSL with custom shadeops.

Is it in the milestones? 

How one would go about it in the current state of the package, let's say, to implement a new type of texture lookup shadeop?

thank you

**Comment by lgritz** [comment]
For a renderer that uses OIIO's texture system, the right way to do this is just to make an ImageInput that looks like an ordinary image reader, but is actually getting tiles via a connection to Substance rather than reading from a disk file. Then NOTHING needs to change in OSL, and we don't have to open the Pandora's Box of custom shadeops.

A few other bits on the renderer side: You'd want to "seed" the TextureSystem to tell it that your texture in question should use the special Substance-communicating ImageInput to read (there is already an API call that lets you make such requests). And you probably want some way for Substance to communicate back to the renderer to tell it which textures and tiles need to be "invalidated" as the paint strokes occur (there's an API call already for that as well).

**Comment by lgritz** [comment]
If you want an example of how this can work, look at OSL's src/osl.imageio directory which contains source for a custom ImageInput plugin that executes OSL to generate the pixels for an "image", rather than read from a disk file. The principle here is the same -- what looks like reads to an image to the texture system, is actually executing a procedure on demand to generate those tiles, without disk I/O.

**Comment by virtualritz** [comment]
Ok, but this does require both access to the renderer's source code and the renderer using OIIO and not it's own texture backend for OSL, right?

**Comment by aghiles** [comment]
I think we could provide such "streaming" textures in 3Delight indeed. Basically, it would become an extension of the texture system and not an extension to OSL.

**Comment by pleprince** [comment]
This is exactly how we did it in RenderMan. A rtx dso that looks and acts like a texture for all intents and purposes. Our patterns have zero knowledge of the specificity of the texture. Good to hear this is doable in osl too: I was wondering about it. (Hi Moritz)

--
Philippe

**Comment by lgritz** [comment]
Closing, I don't think there are any remaining questions or fixes to pursue from this discussion.
