### ISSUE TITLE
Signed/Unsigned Mismatch errors

### ISSUE THREAD

**Issue by ldo** [imageworks/OpenShadingLanguage#552]
I have been trying to build against LLVM 3.5, and found the following signed/unsigned type-mismatch errors.

    diff --git a/src/liboslexec/shadingsys.cpp b/src/liboslexec/shadingsys.cpp
    index b3e1cf5..3907222 100644
    --- a/src/liboslexec/shadingsys.cpp
    +++ b/src/liboslexec/shadingsys.cpp
    @@ -1990,7 +1990,7 @@ ShadingSystemImpl::ShaderGroupBegin (string_view groupname,
                 }
                 // Zero-pad if we parsed fewer values than we needed
                 intvals.resize (type.numelements()*type.aggregate, 0);
    -            ASSERT (type.numelements()*type.aggregate == int(intvals.size()));
    +            ASSERT (type.numelements()*type.aggregate == intvals.size());
                 Parameter (paramname, type, &intvals[0], lockgeom);
             } else if (type.basetype == TypeDesc::FLOAT) {
                 floatvals.clear ();
    @@ -2010,7 +2010,7 @@ ShadingSystemImpl::ShaderGroupBegin (string_view groupname,
                 }
                 // Zero-pad if we parsed fewer values than we needed
                 floatvals.resize (type.numelements()*type.aggregate, 0);
    -            ASSERT (type.numelements()*type.aggregate == int(floatvals.size()));
    +            ASSERT (type.numelements()*type.aggregate == floatvals.size());
                 Parameter (paramname, type, &floatvals[0], lockgeom);
             } else if (type.basetype == TypeDesc::STRING) {
                 stringvals.clear ();
    @@ -2040,7 +2040,7 @@ ShadingSystemImpl::ShaderGroupBegin (string_view groupname,
                 }
                 // Zero-pad if we parsed fewer values than we needed
                 stringvals.resize (type.numelements()*type.aggregate, ustring());
    -            ASSERT (type.numelements()*type.aggregate == int(stringvals.size()));
    +            ASSERT (type.numelements()*type.aggregate == stringvals.size());
                 Parameter (paramname, type, &stringvals[0], lockgeom);
             }

**Comment by ldo** [comment]
Turns out there are even more errors than this, all as a result of treating warnings as errors. To fix them all, I replace the above patch with this:

    diff --git a/CMakeLists.txt b/CMakeLists.txt
    index d8fef04..088c6a0 100644
    --- a/CMakeLists.txt
    +++ b/CMakeLists.txt
    @@ -160,6 +160,10 @@ if (CMAKE_COMPILER_IS_GNUCC AND (NOT CMAKE_COMPILER_IS_CLANG))
             # suppress a warning that Boost::Python hits in g++ 4.8
             add_definitions ("-Wno-error=unused-local-typedefs")
             add_definitions ("-Wno-unused-local-typedefs")
    +        add_definitions ("-Wno-error=strict-overflow")
    +        add_definitions ("-Wno-error=sign-compare")
    +        add_definitions ("-Wno-error=unused-but-set-variable")
    +        add_definitions ("-std=c++11")
         endif ()
     endif ()

**Comment by lgritz** [comment]
If you just want to do these things on your end, you can already compile with

    make USE_CPP11=1 STOP_ON_WARNING=0

and that will achieve the same thing without needing to change things for anybody else.

Not everybody is on C++11 yet, so we can't unconditionally force C++11 like you've done.

I would prefer that we fix all the individual warnings, rather than make the compiler ignore them (if at all possible). The reasons for this are:

1. A warning might be indicating an actual logic bug in our code, so we should examine them individually rather than make it so they never come to our attention.

2. Suppressing warnings across the board is fine for a standalone app is fine (notwithstanding (1) above), but in a library it's asking for trouble because our headers will be included in the compilation of other  projects that might not suppress the warnings. So it is potentially just pushing the problem to other projects.

There are a few places where we suppress warnings entirely, as you saw, but I think that they are all cases where the warnings are in 3rd party library headers, so we can't address them directly by fixing our own code.

Which compiler are you using?

**Comment by lgritz** [comment]
By the way, the warnings originally reported in this issue have long since been fixed in the current master. Sorry, we seem to have forgotten to close the issue when we did it.

Do you need this backported to a release branch?

**Comment by ldo** [comment]
I was just trying to find any branch/tag that would build at all. I want to use it with Blender.

**Comment by lgritz** [comment]
Doesn't Blender have automatic dependency building, so it should know which version to fetch and build?
http://wiki.blender.org/index.php/Dev:Doc/Building_Blender/Linux/Ubuntu/CMake#2._Install_the_dependencies

**Comment by ldo** [comment]
Hmm, that’s a [fork](https://github.com/Nazg-Gul/OpenShadingLanguage). Yeah, maybe I should try it.

I run Debian Unstable, not Ubuntu, so I do my own Blender builds.

**Comment by ldo** [comment]
Given that you have fixed the issues in master, and I can get around them anyway with the command-line option you specified, might as well close this.
