### ISSUE TITLE
Building with -DBUILDSTATIC:BOOL=TRUE fails in 1.7.2

### ISSUE THREAD

**Issue by leafnunes** [imageworks/OpenShadingLanguage#644]
> ld: ../liboslexec/liboslexec.a(shadingsys.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

This happens with or without having built shared in a different build directory, with or without ccache enabled.

**Comment by lgritz** [comment]
Not sure what's up with this, and apologies for not directly replying as soon as it was filed. But there was no follow-up on this and it was a couple versions ago, so closing the issue. Please file a new issue if the current OSL has trouble building. 

(Actually, better advice is: ask on osl-dev if you are merely having trouble building, then file an issue if people agree that it's because of some kind of shortcoming in our build scripts.)
