### ISSUE TITLE
Rebased release branch?

### ISSUE THREAD

**Issue by larsxschneider** [imageworks/OpenShadingLanguage#872]
Hi,

I've cloned this repo in Nov 2017 and updated it today. I noticed that you have rewritten your release branch. My last commit was 44775a9b7f5cc00b4e69dc075fa020a808a2682e which seems to have been rewritten to 806e399c3fb9acf82bbf98b6b56735c463ac3d8b .

Was/is this intentional?

Thanks,
Lars

**Comment by lgritz** [comment]
It was probably a mistake. Since that commit is docs only, I'm guessing that I pushed an earlier version of the edits, realized I still had uncommitted changes, and then right away did a `git commit --amend` and `push --force`. I probably did so absentmindedly like I would in my own tree and either not appreciating that I shouldn't do that on a publicly visible branch, or hoping that nobody had cloned during that short time period that the earlier, wrong, commit was visible. Bad idea. Sorry for the inconvenience.

**Comment by larsxschneider** [comment]
No worries at all. I just wanted to let you know about it just in case it was not intentional or a bad actor involded. BTW: I don't think it was an `--amend` situation. All commits since 92d9eaefc6f461290b3fc42cf10b2cb854ca172f have been rewritten.

If you want to, you can protect your release branches to guard yourself for the future: https://help.github.com/articles/configuring-protected-branches/ 😄
