### ISSUE TITLE
1.1-1.2X faster rendering by avoiding unncessary shadow shader calls

### ISSUE THREAD

**Issue by ElaraFX** [imageworks/OpenShadingLanguage#893]
Below is my commit:

https://github.com/ElaraFX/OpenShadingLanguage/commit/d319ae6175ad4dd7d6b53d2f44aa1f5f793412fa

But my codebase is very old... Too time consuming to solve conflicts... I think it's better to share the idea here.

**Comment by lgritz** [comment]
This looks really interesting. I can turn this patch into a PR for you, but I still really need a CLA from you guys before I'm allowed to merge it.

**Comment by fpsunflower** [comment]
This optimization is only valid for renderers that only look at the `transparent` closure on `shadow` rays.

I think its better for renderers to implement this optimization themselves because they are the only ones that know what the different closures mean with respect to their raytypes.

A related optimization we've talked about in the past but never implemented was do provide a way for renderers to advertise the list of closures they will be looking for (for example, for shadow ray shaders it could be just the "transparent" closure in many cases). Then the optimizer would be free to turn any other closure calls it finds into no-ops, thus triggering extra optimizations. In that case the shader writer might not even need to litter their code with `raytype()` queries at all.

**Comment by ElaraFX** [comment]
I totally agree with @fpsunflower 

What he's suggesting is what we're trying to do next... We found a large potential by doing this because we can turn constant transparent shader into a cached opacity value. this would be a huge optimization for scenes with many glass materials.

@lgritz Please mail CLA to me. My mail address is 43492276@qq.com (I remember I signed CLA for OpenImageIO already...)

**Comment by lgritz** [comment]
[Individual CLA](http://opensource.imageworks.com/cla/pdf/Imageworks_Contributor_License_Agreement_Individual.pdf)

[Corporate CLA](http://opensource.imageworks.com/cla/pdf/Imageworks_Contributor_License_Agreement_Corporate.pdf).

**Comment by lgritz** [comment]
Scanned, signed CLAs can be emailed to opensource@imageworks.com

**Comment by ElaraFX** [comment]
@lgritz Sent the CLAs.

**Comment by lgritz** [comment]
Did you? To that address mentioned above? I didn't see it. Can you try again? Or directly to me: lg AT imageworks.com?

**Comment by ElaraFX** [comment]
@lgritz Sent again to both opensource and lg AT imageworks.com
Still not working?

**Comment by lgritz** [comment]
Yes, got it this time.

I think you've changed userids or emails over the years, I didn't realize you had already send in a CLA.

**Comment by lgritz** [comment]
As far as this issue, I think we are all in agreement here that your patch -- while a good idea -- has the potential to break other renderers, and in the long term we should be aiming for the more general solution (where renderers communicate the set of closures interesting to them for each ray type, rather than those associations being hard-coded as in your original patch).

**Comment by ElaraFX** [comment]
@lgritz No problem. Looking forward to the general solution. So I'm closing this one.
